### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by ArkaPrabhaChowdhury** [open-sauced-craftwork/browser-extension#10]
![image](https://user-images.githubusercontent.com/92904175/224554942-e4655418-40a2-41eb-b09d-3657fb32649a.png)

I believe it should be "The final solution should only show a button **of** the GitHub user profile if the GitHub user is signed up for OpenSauced". 

Would love to fix this.

**Comment by bdougie** [comment]
If still present, feel free to open the PR
