### ISSUE TITLE
No feedback branch 

### ISSUE THREAD

**Issue by siddhart1o1** [open-sauced-craftwork/browser-extension#48]
When I applied for project, my repo didn't have a feedback branch and there was only one branch, “main”, so I pushed the code on the main branch. Hope this will not have any problem.
I completed the assignment and pushed on the main branch of my private repo.

**Comment by nickytonline** [comment]
@siddhart1o1 you need to create a branch to receive feedback. See https://github.com/open-sauced-craftwork/browser-extension/discussions/18#discussioncomment-5302853. The README file of the project mentions this.

**Comment by siddhart1o1** [comment]
> @siddhart1o1 you need to create a branch to receive feedback. See [#18 (comment)](https://github.com/open-sauced-craftwork/browser-extension/discussions/18#discussioncomment-5302853). The README file of the project mentions this.

Yes, I created a new branch and pushed the code on the Branch and pulled it to main branch. But my repo doesn't have class-room's feedback branch, which is in other projects like this. Which is automatically created by bot.
![image](https://user-images.githubusercontent.com/59279771/228258422-336ebeff-853e-4e77-8061-f71589d1f3aa.png)
