### ISSUE TITLE
Update: Feedback PR

### ISSUE THREAD

**Issue by bdougie** [open-sauced-craftwork/browser-extension#9]
There has been some confusion on where the feedback PR is generated. When creating this assignment in Classroom that was turned off. Instead you will need to manually make a PR to the main branch. 

This was resolved in this [Discussion #8](https://github.com/open-sauced-craftwork/browser-extension/discussions/8).

If you have made changes to the main branch and not on a new branch, run the following in the command line on the main branch. 

Please feel free to mention me @bdougie if you have questions. 

```
git remote add upstream https://github.com/open-sauced-craftwork/browser-extension
git branch -m development
git push origin develop
git fetch upstream main
git checkout --track upstream/main
git push origin main -f

```

After running these commands in succession you will be able to open the PR on your repo. That will allow me to review your code. 

Don’t forget to sign up to open sauced by [connecting your GitHub account](https://insights.opensauced.pizza/start) if you haven’t yet.

**Comment by newtonfav** [comment]
Hi, @bdougie I just finished working on my code would love you to review it, thanks.

**Comment by newtonfav** [comment]
> Can you open a PR?

a PR on the private repo given to me?

**Comment by ritikranjan12** [comment]
I opened a PR on the private repo yesterday so you can look it over. Thanks

https://github.com/open-sauced-craftwork/open_sauced_craftwork_browser_extension-ritikranjan12

**Comment by siddhart1o1** [comment]
@bdougie I completed the assignment and pushed on my private repo, please have a look and provide feedback, thanks!
